-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 16:36:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema billyshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `billyshop` ;

-- -----------------------------------------------------
-- Schema billyshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `billyshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `billyshop` ;

-- -----------------------------------------------------
-- Table `billyshop`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`cart` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`cart` (
  `userid` INT NOT NULL,
  `proid` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`proid`, `userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`category` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`category` (
  `cate_id` INT NOT NULL AUTO_INCREMENT,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`cate_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`order_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`order_detail` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`order_detail` (
  `pro_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `discount` FLOAT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `pro_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`orders` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `currency` VARCHAR(255) NULL DEFAULT NULL,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `payment_method` VARCHAR(255) NULL DEFAULT 'standard',
  `shipping_method` VARCHAR(255) NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `userid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FKdxew8n76x1bnoxjas0qxrlbq6` (`userid` ASC) VISIBLE,
  CONSTRAINT `FKdxew8n76x1bnoxjas0qxrlbq6`
    FOREIGN KEY (`userid`)
    REFERENCES `billyshop`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`product` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`product` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `image_link` VARCHAR(1000) NULL DEFAULT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `price` FLOAT NOT NULL,
  `sale` INT NOT NULL DEFAULT '0',
  `stock` INT NOT NULL DEFAULT '1000',
  `cate_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`pro_id`),
  INDEX `FKll9b6w9lwjkhiymqatom6jbd` (`cate_id` ASC) VISIBLE,
  CONSTRAINT `FKll9b6w9lwjkhiymqatom6jbd`
    FOREIGN KEY (`cate_id`)
    REFERENCES `billyshop`.`category` (`cate_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`promotion` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`promotion` (
  `promotion_id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  `discount_rate` INT NULL DEFAULT NULL,
  `is_active` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`promotion_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`rating` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`rating` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `display` INT NOT NULL,
  `nickname` VARCHAR(255) NULL DEFAULT NULL,
  `platform` VARCHAR(255) NULL DEFAULT NULL,
  `rate` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `FKgwxvkm472iugnbp7yrjg5ioou` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKgwxvkm472iugnbp7yrjg5ioou`
    FOREIGN KEY (`user_id`)
    REFERENCES `billyshop`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`role` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` ENUM('ADMIN', 'GUEST', 'SHIPPER', 'USER', 'MANAGER') NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`user` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `active` BIT(1) NULL DEFAULT b'0',
  `address` VARCHAR(1000) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `is_admin` TINYINT(1) NULL DEFAULT '0',
  `is_enabled` BIT(1) NULL DEFAULT b'1',
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `password_salt` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UKob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK589idila9li6a4arw1t8ht1gx` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `UKsb8bbouer5wak8vyiiy4pf2bx` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `billyshop`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `billyshop`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `billyshop`.`users_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `FKj53n5vhpbsurvdnj9y1x4p0id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKgd3iendaoyh04b95ykqise6qh`
    FOREIGN KEY (`user_id`)
    REFERENCES `billyshop`.`user` (`user_id`),
  CONSTRAINT `FKj53n5vhpbsurvdnj9y1x4p0id`
    FOREIGN KEY (`role_id`)
    REFERENCES `billyshop`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
